export const USER_COMPANIES = 'USER_COMPANIES'
export const USER_LIST = 'USER_LIST'
export const USER_DETAIL = 'USER_DETAIL'
export const USER_ADD = 'USER_ADD'
export const USER_EDIT = 'USER_EDIT'
export const USER_DELETE = 'USER_DELETE'
export const PERMISSIONS = 'PERMISSIONS'
